import java.io.*;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.util.stream.Collectors;

public class MP0 {
    Random generator;
    String userName;
    String delimiters = "[\\t,;.:?!\\-@\\[\\](){}_*/ ]";
    String[] stopWordsArray = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours",
            "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its",
            "itself", "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that",
            "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having",
            "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while",
            "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before",
            "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again",
            "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each",
            "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than",
            "too", "very", "s", "t", "can", "will", "just", "don", "should", "now"};

    public MP0(String userName) {
        this.userName = userName;
    }


    public Integer[] getIndexes() throws NoSuchAlgorithmException {
        Integer n = 10000;
        Integer number_of_lines = 50000;
        Integer[] ret = new Integer[n];
        long longSeed = Long.parseLong(this.userName);
        this.generator = new Random(longSeed);
        for (int i = 0; i < n; i++) {
            ret[i] = generator.nextInt(number_of_lines);
        }
        return ret;
    }

    public String[] process() throws Exception{
    	String[] topItems = new String[20];
        Integer[] indexes = getIndexes();
        Map<String, Integer> wordCounts = new HashMap<>();

        // For binary search later on
        Arrays.sort(stopWordsArray);

    	// Read in the input.txt from STDIN
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in, "UTF-8"));

        // Create array of lines from reader
        Object[] lines = reader.lines().toArray();
        lines.
//        final long start = System.currentTimeMillis();

        Arrays.stream(indexes)
              .parallel()
              .mapToInt(i -> i)                                                                     // Unbox the primitive ints....    D^:<
              .mapToObj(i -> lines[i])                                                              // Collect selected lines
              .flatMap(i -> Arrays.stream(((String)i).toLowerCase().split(delimiters)))             // lowercase and split, then merge
              .filter(i -> Arrays.binarySearch(stopWordsArray, (String)i) < 0 && !i.equals(""))     // exclude stopwords and empty strings generated by split
              .collect(Collectors.toList())                                                         // combine threads
              .forEach(i -> wordCounts.put(i, wordCounts.getOrDefault(i, 0)+1));          // increment word counts

//        final long end = System.currentTimeMillis();

//        System.out.println(end - start);

        // Define datastructure that will maintain the desired ordering
        TreeSet<Map.Entry<String, Integer>> wordCountsSet = new TreeSet<>((o1, o2) -> {
            int res;

            // Sort by Key if Values are the same
            if (o1.getValue().equals(o2.getValue())){

                res = o1.getKey().compareTo(o2.getKey());

            } else { // sort by Value, in descending order

                res = -1 * o1.getValue().compareTo(o2.getValue());
            }

            return res;
        });

        // Populate our datastructure with our entries from wordCounts
        wordCountsSet.addAll(wordCounts.entrySet());

        // For iterating over our results set
        Iterator itr = wordCountsSet.iterator();

        // populate topItems with top 20 results
        for (int i = 0; i < topItems.length; i++){

            Object entry = itr.next();

            @SuppressWarnings("unchecked") // I'm a bad boy who does bad casting...
            String theKey = ((Map.Entry<String, Integer>)entry).getKey();

//            System.out.println(((Map.Entry<String, Integer>) entry).getKey() + ":" +((Map.Entry<String, Integer>) entry).getValue());
            topItems[i] = theKey;
        }

		return topItems;
    }

    public static void main(String args[]) throws Exception {
    	if (args.length < 1){
    		System.out.println("missing the argument");
    	}
    	else{
    		String userName = args[0];
	    	MP0 mp = new MP0(userName);
	    	String[] topItems = mp.process();

	        for (String item: topItems){
	            System.out.println(item);
	        }
	    }
	}

}
